// import type { Metadata } from "next"
// import { Aclonica, Poppins, Unbounded } from "next/font/google"
// import 'aos/dist/aos.css';
// import 'swiper/css'
// import "swiper/css/navigation"
// import "swiper/css/pagination"
// import "/public/assets/css/animate.min.css"
// import "/public/assets/css/aos.css"
// import "/public/assets/css/bootstrap.min.css"
// import "/public/assets/css/default.css"
// import "/public/assets/css/fontawesome-all.min.css"
// import "/public/assets/css/icon-font.css"
// import "/public/assets/css/magnific-popup.css"
// import "/public/assets/css/select2.min.css"
// import "/public/assets/css/style.css"
// import "/public/assets/css/swiper-bundle.min.css"

// const poppins = Poppins({
//     weight: ['300', '400', '500', '600', '700'],
//     subsets: ["latin"],
//     variable: "--tg-body-font-family",
//     display: 'swap',
// })
// const aclonica = Aclonica({
//     weight: ['400'],
//     subsets: ["latin"],
//     variable: "--tg-heading-font-family",
//     display: 'swap',
// })
// const unbounded = Unbounded({
//     weight: ['300', '400', '500', '600', '700'],
//     subsets: ["latin"],
//     variable: "--tg-heading2-font-family",
//     display: 'swap',
// })

// export const metadata: Metadata = {
//     title: "Brave Moor | Marketing That Moves Revenue",
//     description: "Generated by Brave Moor",
// }

// export default function RootLayout({
//     children,
// }: Readonly<{
//     children: React.ReactNode
// }>) {
//     return (
//         <html lang="en">
//             <body className={`${poppins.variable} ${aclonica.variable} ${unbounded.variable} theme-green`}>{children}</body>
//         </html>
//     )
// }


import type { Metadata } from "next";
import { Aclonica, Poppins, Unbounded } from "next/font/google";
import Script from "next/script";
import 'aos/dist/aos.css';
import 'swiper/css';
import "swiper/css/navigation";
import "swiper/css/pagination";
import "/public/assets/css/animate.min.css";
import "/public/assets/css/aos.css";
import "/public/assets/css/bootstrap.min.css";
import "/public/assets/css/default.css";
import "/public/assets/css/fontawesome-all.min.css";
import "/public/assets/css/icon-font.css";
import "/public/assets/css/magnific-popup.css";
import "/public/assets/css/select2.min.css";
import "/public/assets/css/style.css";
import "/public/assets/css/swiper-bundle.min.css";
import ChatPanel from "./api/tony/ChatPanel";

// tony assistance
// import TonyAssistant from "@/components/chat/TonyAssistant";


const poppins = Poppins({
  weight: ['300', '400', '500', '600', '700'],
  subsets: ["latin"],
  variable: "--tg-body-font-family",
  display: 'swap',
});

const aclonica = Aclonica({
  weight: ['400'],
  subsets: ["latin"],
  variable: "--tg-heading-font-family",
  display: 'swap',
});

const unbounded = Unbounded({
  weight: ['300', '400', '500', '600', '700'],
  subsets: ["latin"],
  variable: "--tg-heading2-font-family",
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Brave Moor | Marketing That Moves Revenue",
  description:
    "Brave Moor helps ambitious brands earn trust, build loyalty, and drive measurable revenue through strategy, design, and digital marketing.",
  keywords: [
    "digital marketing agency",
    "Brave Moor",
    "SEO services",
    "social media marketing",
    "web design",
    "branding",
    "Google ads",
    "email marketing",
    "marketing automation",
  ],
  authors: [{ name: "Brave Moor" }],
  creator: "Brave Moor",
  publisher: "Brave Moor",
  robots: "index, follow",
  verification: {
    google: "google9e092a46e8ff00ac", // ✅ Google Search Console verification
  },
  openGraph: {
    title: "Brave Moor — Building Brands That Matter",
    description:
      "We help ambitious brands earn trust that converts into long-term growth and measurable revenue.",
    url: "https://www.bravemoor.com",
    siteName: "Brave Moor",
    images: [
      {
        url: "https://www.bravemoor.com/assets/img/logo/bravemoor-logo.png",
        width: 800,
        height: 600,
        alt: "Brave Moor Logo",
      },
    ],
    locale: "en_US",
    type: "website",
  },
};

// ✅ Root Layout with Analytics & Fonts
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        {/* Google Analytics (optional — replace with your real GA ID) */}
        <Script
          async
          src="https://www.googletagmanager.com/gtag/js?id=G-XXXXXXXXXX"
        />
        <!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-SLE0VJHTYF"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-SLE0VJHTYF');
</script>
      </head>

      <body
        className={`${poppins.variable} ${aclonica.variable} ${unbounded.variable} theme-green`}
      >
        {children}

        <div style={{ position: "fixed", right: 20, bottom: 24, zIndex: 9999 }}>
  <ChatPanel />
</div>
      </body>
    </html>
  );
}
